blank_issues_enabled: true
contact_links:
  - name: Discussions
    url: discussions
    about: For other types of questions, consider using Discussions.
  - name: Issue Management Policies
    url: IssueManagementPolicies.md
    about: More information on our issue management policies is available here.
